CREATE TABLE IF NOT EXISTS workouts (
  workout_id INTEGER PRIMARY KEY,
  owner INTEGER NOT NULL,
  name TEXT NOT NULL,
  FOREIGN KEY (owner)
    REFERENCES users (user_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);
