kind: Deployment
apiVersion: apps/v1
metadata:
  name: musclemem-api
  labels:
    app.kubernetes.io/name: musclemem-api
    app.kubernetes.io/part-of: musclemem
    app.kubernetes.io/component: api
    app.kubernetes.io/version: "latest"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: musclemem-api
      app.kubernetes.io/part-of: musclemem
  template:
    metadata:
      labels:
        app.kubernetes.io/name: musclemem-api
        app.kubernetes.io/part-of: musclemem
        app.kubernetes.io/component: api
        app.kubernetes.io/version: "latest"
    spec:
      containers:
      - name: musclemem-api
        image: ghcr.io/scrot/musclemem-api:latest 
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred
